### ISSUE TITLE
Dataflow Builder

### ISSUE THREAD

**Issue by oportier** [code-rhapsodie/dataflow-bundle#32]
In the documentation, you say:

> To help with creating your dataflow types, an abstract class CodeRhapsodie\DataflowBundle\DataflowType\AbstractDataflowType is provided, allowing you to define your dataflow through a handy builder CodeRhapsodie\DataflowBundle\DataflowType\DataflowBuilder.

Is there a command line builder to generate a generic Dataflow ? That would be handfull ;)

**Comment by jeremycr** [comment]
I'll assume you are talking about a DataflowType skeleton. It would look like this :
```php
<?php

declare(strict_types=1);

namespace App\WorkflowType;

use CodeRhapsodie\DataflowBundle\DataflowType\AbstractDataflowType;
use CodeRhapsodie\DataflowBundle\DataflowType\DataflowBuilder;

class GenericDataflowType extends AbstractDataflowType
{
    public function getLabel(): string
    {
        // TODO: Implement getLabel() method.
    }

    protected function buildDataflow(DataflowBuilder $builder, array $options): void
    {
        // TODO: Implement buildDataflow() method.
    }
}

```

We currently have no plan of writing a command that would generate code.

You can look at this [example](https://github.com/code-rhapsodie/dataflow-example/blob/master/src/DataflowType/MyFirstDataflowType.php) to get an idea of what a complete dataflow type would look like.

If you need generic readers and writers, you can use those provided by [PortPHP](https://github.com/portphp/portphp).
